# Este playbook permite realizar una instalacion de un archivo ZIP en un servidor IIS reiniciando el pool
# existente y realizando el copiado de los archivos correspondiente. 

---
- name: Install IIS DotNet Framework App
  hosts: all
  tasks:
    - name: Set the shell type to PowerShell
      set_fact:
        ansible_shell_type: powershell
        ansible_shell_executable: None

    - name: Return information about an existing application pool
      community.windows.win_iis_webapppool:
        name: '{{ appPoolName }}'
        state: present

    - name: Stop IIS application pool
      community.windows.win_iis_webapppool:
        name: '{{ appPoolName }}'
        state: stopped
    
    - name: Create a new directory
      win_file:
        path: 'D:\ansible\installation\'
        state: directory

    - name: Copy deploy.zip to the host
      win_copy:
        src: '{{ artifactPath }}/deploy.zip'
        dest: 'D:\ansible\installation\deploy.zip'
        overwrite: yes

    - name: Delete all files in the directory
      win_shell: Remove-Item -Path '{{ installPath }}\*' -Force -Recurse
    
    - name: Unzip deploy.zip
      win_unzip:
        src: 'D:\ansible\installation\deploy.zip'
        dest: '{{ installPath }}'
        overwrite: yes

    - name: Start IIS application pool
      community.windows.win_iis_webapppool:
        name: '{{ appPoolName }}'
        state: started
